version: "3"

services:
  adminer:
    image: adminer
    container_name: adminer
    restart: always
    networks:
      - adminer
    ports:
      - 8080:8080
    environment:
      ADMINER_DESIGN: flat

networks:
  adminer:
    external: true

