version: "3"

services:
  mysql:
    image: mysql:5.7
    restart: always
    volumes:
      - data:/var/lib/mysql
    networks:
      - backend
    environment:
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}

  wordpress:
    image: wordpress
    restart: always
    depends_on:
      - mysql
    networks:
      - proxy
      - backend
    environment:
      VIRTUAL_HOST: ${DOMAIN_NAME}
      LETSENCRYPT_HOST: ${DOMAIN_NAME}
      LETSENCRYPT_EMAIL: ${ADMIN_EMAIL}
      WORDPRESS_DB_HOST: mysql:3306
      WORDPRESS_DB_USER: ${MYSQL_USER}
      WORDPRESS_DB_NAME: ${MYSQL_DATABASE}
      WORDPRESS_DB_PASSWORD: ${MYSQL_PASSWORD}

  cron:
    build: ../cron
    restart: always
    volumes:
      - backup:${BACKUP_PATH}
    depends_on:
      - mysql
    networks:
      - backend
    environment:
      BACKUP_PATH: ${BACKUP_PATH}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_HOST: mysql

volumes:
  data:
  backup:

networks:
  proxy:
    external: true
  backend:

