version: "3"

services:
  mysql:
    image: mysql:5.7
    container_name: ghost_mysql
    restart: always
    volumes:
      - data:/var/lib/mysql
    networks:
      - adminer
      - backend
    environment:
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}

  ghost:
    image: ghost:2-alpine
    restart: always
    depends_on:
      - mysql
    networks:
      - proxy
      - backend
    environment:
      VIRTUAL_HOST: ${DOMAIN_NAME}
      LETSENCRYPT_HOST: ${DOMAIN_NAME}
      LETSENCRYPT_EMAIL: ${ADMIN_EMAIL}
      NODE_ENV: production
      url: https://${DOMAIN_NAME}
      database__client: mysql
      database__connection__host: ghost_mysql
      database__connection__user: ${MYSQL_USER}
      database__connection__database: ${MYSQL_DATABASE}
      database__connection__password: ${MYSQL_PASSWORD}

  cron:
    build: ../cron
    restart: always
    volumes:
      - backup:${BACKUP_PATH}
    depends_on:
      - mysql
    networks:
      - backend
    environment:
      BACKUP_PATH: ${BACKUP_PATH}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_HOST: ghost_mysql

volumes:
  data:
  backup:

networks:
  adminer:
    external: true
  proxy:
    external: true
  backend:

